### PR TITLE
Displayed and Styled Role Id

### LINKED ISSUE #23: Display and Style Role Identifiers
Clearly display to the user whether the person that published a topic is an instructor or a student.

### PR DESCRIPTION
**Pull request by TyreceDJ**
Resolves #23

### CODE REVIEW

**Comment by TyreceDJ** [comment]
Here's how the changes look

slides_role_curr

I would have liked to change the color based on whether it was a teacher or a student however that would require an addition boolean field supplied to the tpl file through the api.

**Comment by connormaas-cmu** [comment]
Look good!

**Review by connormaas-cmu — APPROVED** [review]
Looks good

**Comment by TyreceDJ** [comment]
Tests passed initially, but the pull request was closed and reopened resulting in the testing running again. Changes were merged before the second test run was completed.

**Pull request merged**
